site_name: P1 Robótica
use_directory_urls: false

nav:
- 'Teoría':
   - 'Descripción de la asignatura': 'Teoria/tema00-descripcion-asignatura/tema00-descripcion-asignatura.md'
   - 'Tema 1': 'Teoria/tema01-introduccion-a-la-programacion/tema01-introduccion-a-la-programacion.md'

theme:
    language: es
    name: 'material'
    palette:
        primary: 'Teal'
        accent: 'Teal'
    font:
        text: 'Roboto'
        code: 'Roboto Mono'
    logo: 'imagenes/logo.png'

# Ponemos como idioma de búsqueda el inglés
# para conseguir que busque correctamente
# todas las palabras en castellano, sin eliminar
# los excesivos derivados que se definen en
# https://github.com/MihaiValentin/lunr-languages/blob/master/lunr.es.js

extra:
    search:
        language: 'en'

markdown_extensions:
    - admonition
    - codehilite:
        linenums: true
    - footnotes
    - meta
    - sane_lists
    - toc:
       permalink: true
       toc_depth: 3
    - pymdownx.superfences
